//! Squisher Attack: Massively parallel GF(2) matrix extraction for WB-AES
//!
//! This Rust crate attacks the WBAES SEC_PROT Phase 1 "squisher" — the compression
//! function that takes 128 bytes of AES ciphertext and produces 20 bytes of output.
//!
//! Strategy (from academic literature):
//!   1. The Chow WB-AES uses affine bijections (linear + constant over GF(2))
//!   2. If the squisher is GF(2)-linear, f(x) = M*x + c where M is 160×1024 bits
//!   3. We extract M by probing all 1024 basis vectors: column_i = f(e_i) XOR f(0)
//!   4. Once M is known, the 353K-instruction squisher becomes a matrix multiply
//!
//! Architecture:
//!   - Go side: runs the WBAES emulator to compute f(payload) for each probe
//!   - Rust side: orchestrates probes, extracts matrix, verifies, and generates
//!     the final compact Go implementation
//!
//! Based on:
//!   - BGE attack (Billet, Gilbert, Ech-Chatbi, 2004)
//!   - Affine equivalence algorithms (Biryukov et al.)
//!   - Collision-based sparse linear system attacks (Rivain et al.)

use std::io::{BufRead, BufReader, Write};
use std::process::{Command, Stdio};
use std::sync::Arc;
use std::time::Instant;

/// A 160-bit (20-byte) column vector over GF(2)
type Col160 = [u8; 20];

/// The full GF(2) affine matrix: f(x) = M*x + constant
/// M is 160 rows × 1024 columns (20 bytes per column, 1024 columns)
struct AffineMatrix {
    /// The constant term: f(zero_vector)
    constant: Col160,
    /// Matrix columns: matrix[bit_index] = f(e_i) XOR f(0)
    /// where e_i has only bit `bit_index` set
    columns: Vec<Col160>,
}

impl AffineMatrix {
    /// Apply the matrix to an input: result = M*input + constant
    fn apply(&self, input: &[u8; 128]) -> Col160 {
        let mut result = self.constant;
        for bit in 0..1024 {
            let byte_idx = bit / 8;
            let bit_idx = bit % 8;
            if (input[byte_idx] >> bit_idx) & 1 == 1 {
                for j in 0..20 {
                    result[j] ^= self.columns[bit][j];
                }
            }
        }
        result
    }

    /// Compute matrix rank (number of linearly independent columns)
    fn rank(&self) -> usize {
        // Gaussian elimination over GF(2) on transposed matrix
        let mut rows: Vec<[u8; 128]> = Vec::new(); // 160 rows of 1024 bits each

        for row_bit in 0..160 {
            let mut row = [0u8; 128];
            for col in 0..1024 {
                let col_byte = row_bit / 8;
                let col_bit_in_byte = row_bit % 8;
                if (self.columns[col][col_byte] >> col_bit_in_byte) & 1 == 1 {
                    let row_byte = col / 8;
                    let row_bit_in_byte = col % 8;
                    row[row_byte] |= 1 << row_bit_in_byte;
                }
            }
            rows.push(row);
        }

        // Row echelon form
        let mut rank = 0;
        for col in 0..1024 {
            let col_byte = col / 8;
            let col_bit = col % 8;

            // Find pivot
            let mut pivot = None;
            for row in rank..rows.len() {
                if (rows[row][col_byte] >> col_bit) & 1 == 1 {
                    pivot = Some(row);
                    break;
                }
            }

            if let Some(p) = pivot {
                rows.swap(rank, p);
                // Eliminate
                let pivot_row = rows[rank];
                for row in 0..rows.len() {
                    if row != rank && (rows[row][col_byte] >> col_bit) & 1 == 1 {
                        for b in 0..128 {
                            rows[row][b] ^= pivot_row[b];
                        }
                    }
                }
                rank += 1;
            }
        }

        rank
    }

    /// Generate compact Go code that implements this matrix multiply
    fn generate_go_code(&self) -> String {
        let mut code = String::new();
        code.push_str("package fpemu\n\n");
        code.push_str("// squisherMatrix applies the GF(2) affine matrix to compress\n");
        code.push_str("// 128 bytes of AES-ECB ciphertext into 20 bytes of output.\n");
        code.push_str("// This replaces 353,000 ARM64 instructions with pure math.\n");
        code.push_str("//\n");
        code.push_str("// Generated by squisher_attack (Rust)\n");
        code.push_str("func squisherMatrix(ct [128]byte) [20]byte {\n");
        code.push_str(&format!("\tvar result = [20]byte{{{}}}\n",
            self.constant.iter()
                .map(|b| format!("0x{:02x}", b))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        code.push_str("\n");

        // Group columns by input byte for efficiency
        for byte_idx in 0..128 {
            let mut any_nonzero = false;
            for bit in 0..8 {
                let col = &self.columns[byte_idx * 8 + bit];
                if col.iter().any(|&b| b != 0) {
                    any_nonzero = true;
                    break;
                }
            }
            if !any_nonzero {
                continue;
            }

            code.push_str(&format!("\t// Input byte {}\n", byte_idx));
            code.push_str(&format!("\tb := ct[{}]\n", byte_idx));

            for bit in 0..8u8 {
                let col = &self.columns[byte_idx * 8 + bit as usize];
                if col.iter().all(|&b| b == 0) {
                    continue;
                }

                code.push_str(&format!("\tif b&0x{:02x} != 0 {{\n", 1u8 << bit));
                for j in 0..20 {
                    if col[j] != 0 {
                        code.push_str(&format!("\t\tresult[{}] ^= 0x{:02x}\n", j, col[j]));
                    }
                }
                code.push_str("\t}\n");
            }
            code.push_str("\n");
        }

        code.push_str("\treturn result\n");
        code.push_str("}\n");
        code
    }
}

fn main() {
    println!("╔══════════════════════════════════════════════════╗");
    println!("║  Squisher Attack: GF(2) Matrix Extraction       ║");
    println!("║  Target: WBAES SEC_PROT Phase 1 compression       ║");
    println!("║  Method: 1024 basis vector probes → 160×1024 M  ║");
    println!("╚══════════════════════════════════════════════════╝");
    println!();

    // This binary is designed to be called by the Go test harness.
    // For now, it demonstrates the matrix data structures and Go codegen.
    // The actual probing is done by the Go test (which has access to the emulator).

    println!("This tool processes probe results from the Go emulator.");
    println!("Usage:");
    println!("  1. Run Go test: go test -tags withblob -run TestExtractGF2Matrix");
    println!("  2. Pipe probe results to this tool for matrix analysis + Go codegen");
    println!();

    // Demo: generate Go code for a trivial identity-like matrix
    let mut demo = AffineMatrix {
        constant: [0u8; 20],
        columns: vec![[0u8; 20]; 1024],
    };

    // Set a few demo columns
    for i in 0..20 {
        for bit in 0..8 {
            demo.columns[i * 8 + bit][i] = 1 << bit;
        }
    }

    println!("Demo matrix rank: {}", demo.rank());
    println!("Demo Go code preview (first 20 lines):");
    let code = demo.generate_go_code();
    for (i, line) in code.lines().enumerate() {
        if i < 20 {
            println!("  {}", line);
        }
    }
    println!("  ...");
}
